repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files

  # ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.4"
    hooks:
      - id: ruff
        args: ["--fix"]
