[tool.ruff]
line-length = 99
src = ["src"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ARG",
    "ANN",
    "D",
    "EM101",
    "EM102",
    "PT001",
    "PT023",
    "SIM108",
    "SIM114",
    "TRY003",
    "PLW2901",
    "RET505",
    "PLR0913",
    "FA",
    "S101",
    "PLR2004",
    "TCH001",
    "PGH003",
    "TD001",
    "TD002",
    "TD003",
    "FIX001",
    "FIX002",
    "TCH002",
    "ERA001",
    "N818",
    "E501",
    "PTH118",
    "PERF401",

    # maybe fix :/
    "DTZ005",
    "PTH123",


]
